### ISSUE TITLE
Events Swallowed

### ISSUE THREAD

**Issue by Crisfole** [Prezent/ractive-decorators-select2#9]
Change events are getting swallowed by the select2 decorator.

Try adding `on-change='whatever'` or `on-change='callMethod()'` and you'll see what I mean.

**Comment by sandermarechal** [comment]
This is caused by jQuery and Select2. jQuery does not fire native browser events but jQuery-specific events. This applies to select2 as well. By adding an `on-change` you are asking Ractive to listen to the native `change` event (which isn't triggered).

There are two solutions for this:

1) Listen to the jQuery change event instead. E.g:

    $('select').on('change', function () {
        ractive.fire('whatever');
    });

2) Trigger native HTML events instead. You can use [jquery-simulate](https://github.com/jquery/jquery-simulate/) for this.

For more information about jQuery events, see: https://learn.jquery.com/events/triggering-event-handlers/

**Comment by Crisfole** [comment]
@sandermarechal Thanks! I suppose I never realized that jQuery suppressed the native change events. Makes sense when I think about how I'd implement it...
